@extends('layouts.admin', ['title' => 'Overview', 'heading' => 'Overview'])
@section('content')
<div class="page-intro"><div><span class="eyebrow">Store pulse</span><h2>Good morning, {{ explode(' ', auth()->user()->name)[0] }}.</h2><p>Here is what is happening across your catalogue and orders.</p></div><a href="{{ route('admin.products.create') }}" class="button button-dark">Add product <span>＋</span></a></div>
<section class="metric-grid" aria-label="Store metrics">
    <article class="metric-card metric-card-featured"><span class="metric-label">All-time revenue</span><strong>${{ number_format($revenue, 2) }}</strong><small>Confirmed and fulfilled orders</small><span class="metric-stamp">↗</span></article>
    <article class="metric-card"><span class="metric-label">This month</span><strong>${{ number_format($monthRevenue, 2) }}</strong><small>Revenue this month</small></article>
    <article class="metric-card"><span class="metric-label">Orders</span><strong>{{ number_format($ordersCount) }}</strong><small>Across every status</small></article>
    <article class="metric-card"><span class="metric-label">Customers</span><strong>{{ number_format($customersCount) }}</strong><small>Saved customer profiles</small></article>
</section>
<section class="dashboard-grid">
    <article class="panel sales-panel"><div class="panel-heading"><div><span class="eyebrow">Last 7 days</span><h3>Sales activity</h3></div><span class="panel-meta">USD</span></div><div class="sales-chart">@php($maxSale = max(1, $dailySales->max('value')))<div class="chart-y"><span>${{ number_format($maxSale) }}</span><span>${{ number_format($maxSale / 2) }}</span><span>$0</span></div><div class="chart-bars">@foreach ($dailySales as $day)<div class="bar-column"><div class="bar-wrap"><div class="bar" style="height: {{ max(5, ($day['value'] / $maxSale) * 100) }}%" title="${{ number_format($day['value'], 2) }}"></div></div><span>{{ $day['label'] }}</span></div>@endforeach</div></div></article>
    <article class="panel"><div class="panel-heading"><div><span class="eyebrow">Inventory watch</span><h3>Needs attention</h3></div><a href="{{ route('admin.products.index') }}" class="text-link">View all</a></div>@forelse ($lowStock as $product)<div class="attention-row"><span class="mini-thumb" style="background-image:url('{{ $product->image }}')"></span><div><strong>{{ $product->name }}</strong><small>{{ $product->stock_quantity === 0 ? 'Sold out' : $product->stock_quantity.' units left' }}</small></div><a href="{{ route('admin.products.edit', $product) }}" aria-label="Edit {{ $product->name }}">↗</a></div>@empty<p class="empty-copy">Everything is in stock and up to date.</p>@endforelse</article>
</section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Latest activity</span><h3>Recent orders</h3></div><a href="{{ route('admin.orders.index') }}" class="text-link">Manage orders</a></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th class="align-right">Total</th></tr></thead><tbody>@forelse ($recentOrders as $order)<tr><td><a class="table-link" href="{{ route('admin.orders.show', $order) }}">{{ $order->order_number }}</a></td><td>{{ $order->customer_name }}</td><td>{{ $order->created_at->format('d M Y') }}</td><td><span class="status status-{{ $order->status }}">{{ str_replace('_', ' ', $order->status) }}</span></td><td class="align-right">${{ number_format($order->total, 2) }}</td></tr>@empty<tr><td colspan="5" class="empty-cell">No orders yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
