@php
    $sizeValue = old('sizes', collect($product->sizes ?? [])->join(', '));
    $colorValue = old('colors', collect($product->colors ?? [])->map(fn ($color) => ($color['name'] ?? '').'|'.($color['hex'] ?? '#171717'))->join("\n"));
@endphp
<div class="form-grid">
    <div class="field"><label for="name">Product name</label><input id="name" name="name" value="{{ old('name', $product->name) }}" required></div>
    <div class="field"><label for="slug">Slug <span class="field-hint">Optional, generated from name</span></label><input id="slug" name="slug" value="{{ old('slug', $product->slug) }}" placeholder="amara-wrap-dress"></div>
    <div class="field"><label for="category">Category</label><select id="category" name="category" required>@foreach (['dresses','tops','sets','bottoms','summer','sale'] as $category)<option value="{{ $category }}" @selected(old('category', $product->category) === $category)>{{ ucfirst($category) }}</option>@endforeach</select></div>
    <div class="field"><label for="collection_id">Collection</label><select id="collection_id" name="collection_id"><option value="">No collection</option>@foreach ($collections as $collection)<option value="{{ $collection->id }}" @selected((string) old('collection_id', $product->collection_id) === (string) $collection->id)>{{ $collection->title }}</option>@endforeach</select></div>
    <div class="field full"><label for="description">Description</label><textarea id="description" name="description" required>{{ old('description', $product->description) }}</textarea></div>
    <div class="field full"><label for="care">Care instructions</label><textarea id="care" name="care">{{ old('care', $product->care) }}</textarea></div>
    <div class="field"><label for="price">Price (USD)</label><input id="price" name="price" type="number" step="0.01" min="0" value="{{ old('price', $product->price) }}" required></div>
    <div class="field"><label for="sale_price">Sale price <span class="field-hint">Optional, lower than price</span></label><input id="sale_price" name="sale_price" type="number" step="0.01" min="0" value="{{ old('sale_price', $product->sale_price) }}"></div>
    <div class="field"><label for="sizes">Sizes <span class="field-hint">Comma separated</span></label><input id="sizes" name="sizes" value="{{ $sizeValue }}" placeholder="XS, S, M, L, XL"></div>
    <div class="field"><label for="sort_order">Sort order</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $product->sort_order ?? 0) }}"></div>
    <div class="field"><label for="stock_quantity">Stock quantity</label><input id="stock_quantity" name="stock_quantity" type="number" min="0" value="{{ old('stock_quantity', $product->exists ? $product->stock_quantity : 10) }}" required><span class="field-hint">Ordering is blocked when this reaches zero.</span></div>
    <div class="field full"><label for="colors">Colours <span class="field-hint">One per line: Name|#hex</span></label><textarea id="colors" name="colors" placeholder="Black|#171717&#10;Ivory|#F7F3ED">{{ $colorValue }}</textarea></div>
    <div class="field"><label for="image_upload">Primary image</label><input id="image_upload" name="image_upload" type="file" accept="image/jpeg,image/png,image/webp,image/avif" @required(!$product->exists)>@if ($product->image)<img class="admin-image-preview" src="{{ $product->image }}" alt="Current primary image">@endif<span class="field-hint">{{ $product->exists ? 'Upload a replacement image, up to 5 MB.' : 'Upload a JPG, PNG, WEBP, or AVIF image, up to 5 MB.' }}</span></div>
    <div class="field"><label for="hover_image_upload">Hover image</label><input id="hover_image_upload" name="hover_image_upload" type="file" accept="image/jpeg,image/png,image/webp,image/avif">@if ($product->hover_image)<img class="admin-image-preview" src="{{ $product->hover_image }}" alt="Current hover image"><label class="content-clear"><input name="hover_image_clear" type="checkbox" value="1"> Remove hover image</label>@endif<span class="field-hint">Optional alternate image shown when the product is hovered.</span></div>
    <div class="field full"><label for="gallery_uploads">Gallery images</label><input id="gallery_uploads" name="gallery_uploads[]" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple>@if ($product->gallery)<div class="admin-gallery-previews">@foreach ($product->gallery as $index => $image)<img class="admin-gallery-preview" src="{{ $image }}" alt="Current gallery image {{ $index + 1 }}">@endforeach</div><label class="content-clear"><input name="gallery_clear" type="checkbox" value="1"> Remove current gallery</label>@endif<span class="field-hint">Select multiple images to replace the current gallery. Each file can be up to 5 MB.</span></div>
    <div class="field full"><label>Store visibility</label><div class="check-grid"><label class="check-card"><input type="checkbox" name="in_stock" value="1" @checked(old('in_stock', $product->exists ? $product->in_stock : true))> Available to order</label><label class="check-card"><input type="checkbox" name="is_new" value="1" @checked(old('is_new', $product->is_new))> New arrival</label><label class="check-card"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $product->is_featured))> Featured</label><label class="check-card"><input type="checkbox" name="is_best_seller" value="1" @checked(old('is_best_seller', $product->is_best_seller))> Best seller</label></div></div>
</div>
<div class="form-actions"><a href="{{ route('admin.products.index') }}" class="button button-light">Cancel</a><button type="submit" class="button button-dark">{{ $product->exists ? 'Save changes' : 'Create product' }} <span>↗</span></button></div>
